"""cart model edit

Revision ID: c9db94130b22
Revises: cc64d2de57ef
Create Date: 2025-03-18 09:46:56.319493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9db94130b22'
down_revision: Union[str, None] = 'cc64d2de57ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['productId'], ['products.id'], name=op.f('fk__cart__productId__products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name=op.f('fk__cart__userId__users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__cart'))
    )
    op.drop_table('cart_items')
    op.drop_table('carts')
    op.create_unique_constraint(op.f('uq__orders__id'), 'orders', ['id'])
    op.create_unique_constraint(op.f('uq__reviews__id'), 'reviews', ['id'])
    op.create_unique_constraint(op.f('uq__users__id'), 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__users__id'), 'users', type_='unique')
    op.drop_constraint(op.f('uq__reviews__id'), 'reviews', type_='unique')
    op.drop_constraint(op.f('uq__orders__id'), 'orders', type_='unique')
    op.create_table('carts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='fk__carts__userId__users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk__carts'),
    postgresql_ignore_search_path=False
    )
    op.create_table('cart_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cartId', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('productId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cartId'], ['carts.id'], name='fk__cart_items__cartId__carts', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['productId'], ['products.id'], name='fk__cart_items__productId__products', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk__cart_items')
    )
    op.drop_table('cart')
    # ### end Alembic commands ###
