"""tablename change

Revision ID: 8cff7d4bbcff
Revises: c0d911518219
Create Date: 2025-03-13 19:14:22.185209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cff7d4bbcff'
down_revision: Union[str, None] = 'c0d911518219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_name_key', 'products', type_='unique')
    op.create_unique_constraint(op.f('uq__products__name'), 'products', ['name'])
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_unique_constraint(op.f('uq__users__email'), 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__users__email'), 'users', type_='unique')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_constraint(op.f('uq__products__name'), 'products', type_='unique')
    op.create_unique_constraint('products_name_key', 'products', ['name'])
    # ### end Alembic commands ###
